name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

# Github Clien ID
G_CLIENT_ID=Ov23likNqIzfvqw5M767
# Github Clien Secret
#G_CLIENT_SECRET=
# JWT Secret, 通常就用 Clien Secret
#JWT_SECRET=
# 初始化数据库, 首次运行必须设置为 true，之后可以将其关闭
INIT_TABLE=true
# 是否启用缓存
ENABLE_CACHE=true

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_data"
database_id = "6c3aeae6-eda3-4cb3-93e1-8edaa178eee3"
