name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"


G_CLIENT_ID=Ov23likNqIzfvqw5M767
INIT_TABLE=true
ENABLE_CACHE=true

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_data"
database_id = "6c3aeae6-eda3-4cb3-93e1-8edaa178eee3"
